### PR TITLE
Handle redirect uri`s from config

### PR DESCRIPTION
**Pull request by undefhero**

### CODE REVIEW

**Comment by sonic182** [comment]
This is done already for version 1.6.3 @undefhero, you can check https://github.com/dwyl/elixir-auth-google#different-callback-url

**Comment by nelsonic** [comment]
Hi @undefhero! 👋  
once again, thanks for this PR. 👍 
as noted by @sonic182, this functionality has been added. 📦 
It would still be good to get your contribution merged in _especially_ the tests. ✅ 
If you have time to rebase and update, please do. 🙏 
Or if not, push your branch directly to this repo and we can take a look. 💭 
(_invited you to be a contributor so you have **`write access`**_) 📝 
Thanks! ☀️

**Comment by undefhero** [comment]
@nelsonic Just rebased my branch and also pushed to this repository

**Review by nelsonic — APPROVED** [review]
@undefhero thank you very much for these tests. You are Awesome! 🚀

**Pull request merged**
