### PR TITLE
Read CLIENT_ID and CLIENT_SECRET from Config when not available on system environment

### PR DESCRIPTION
**Pull request by luisguilhermemsalmeida**

### CODE REVIEW

**Comment by nelsonic** [comment]
Hi @luisguilhermemsalmeida thank you for opening this Pull Request.
If you don't mind adding some detail to the `README.md` explaining to people that this optional configuration is available. 

The build is failing because Travis cannot find the optional config:
https://travis-ci.com/github/dwyl/elixir-auth-google/builds/221387450#L244
image

If you can add the docs we can make sure the tests pass and get this merged. 
Thanks.

**Comment by SimonLab** [comment]
One of the test is failing that's why the coverage is not up
image

I'm not sure the failing test is directly linked to the PR. I just tested master and I have a similar error. It might be worth to update the dependencies first

**Comment by luisguilhermemsalmeida** [comment]
Hey guys! Just updated the PR.

I don't think the failing test was directly related to my PR. It was caused by the environment variable not being set on the test environment. What I did instead was to create config files as suggested and assert that both ways will work.

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/elixir_auth_google/1.5.1 📦 (contains this update) 👍

**Pull request merged**
