### PR TITLE
Allow custom query params to oauth url generator

### PR DESCRIPTION
**Pull request by javierg**
We have the requirement to use different languages on the oauth google request, so I couldn't find a way with current implementation, so I modified the `generate_oauth_url/2` to have current behaivor with a `binary` and added a second match for `map` values that translate to a query as it comes.

### CODE REVIEW

**Review by SimonLab — APPROVED** [review]
Code looks good to me.

I tried to find the doc reference on google for the `hl` query parameter but could only find this stackoverflow link https://stackoverflow.com/questions/14271747/what-does-hl-stand-for

This is not a blocker as the `query` map arguments for `generate_oauth_url` can have any values defined by the user and is not specific to the `hl` value.

@nelsonic I let you double check/merge

**Review by nelsonic — APPROVED** [review]
@javierg thanks for this addition. Totally get it that this is to serve your _current_ needs.

My only feedback/notes are:

It would be good to get some docs in the `README.md` or _something_ explaining the use-case somewhere otherwise we're just adding code and nobody knows it's there or how to `use` it ... 🤷‍♂️

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/elixir_auth_google/1.6.5 📦 🚀

**Comment by javierg** [comment]
> @javierg thanks for this addition. Totally get it that this is to serve your current needs.

> My only feedback/notes are:

> It would be good to get some docs in the README.md or something explaining the use-case somewhere otherwise we're just adding code and nobody knows it's there or how to use it ... 🤷‍♂️

Totally Agree, I can do some update to the READ.me file and I would accept to wait the merge until it is done, but I see you merge it already, thanks a lot for that!

**Comment by nelsonic** [comment]
@javierg enhancements/updates to the `README.md`/docs are _always_ welcome. 
You have write access to the repo: https://github.com/dwyl/elixir-auth-google/invitations
And org-wide access to everything: https://github.com/orgs/dwyl/people/pending_invitations

**Pull request merged**
